name: Node CI

on:
  - push
jobs:
  my-job:
    build:
      strategy:
        matrix:
          node-version: [ 14.x ]
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node-version }}
        - name: Run linter
            run: |
              make lint
